2

diff --git a/.github/workflows/nuxtjs.yml b/.github/workflows/nuxtjs.yml
--- a/.github/workflows/nuxtjs.yml
+++ b/.github/workflows/nuxtjs.yml
@@ -1,57 +1,60 @@
-# .github/workflows/deploy.yml
-name: Deploy Nuxt 4 site to Pages
-
+name: Deploy Nuxt site to Pages
 on:
-  # Запуск при пуше в основную ветку
   push:
     branches: ["main"]
-
-  # Возможность ручного запуска
   workflow_dispatch:
-
-# Права доступа для токена GITHUB_TOKEN
 permissions:
   contents: read
   pages: write
   id-token: write
-
-# Ограничение конкурентных запусков
 concurrency:
   group: "pages"
   cancel-in-progress: false
-
 jobs:
-  # Job сборки
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
+        
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+          
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
-          node-version: "20" # Nuxt 4 требует Node.js 18+ или 20+
-          cache: 'npm'       # Включаем кэширование node_modules через npm
-
-      - name: Setup Pages
-        uses: actions/configure-pages@v5
-        with:
-          static_site_generator: nuxt
-
+          node-version: "22"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          
       - name: Install dependencies
-        run: npm install     # Явная установка через npm install
-
-      - name: Build static site (Nuxt Generate)
-        run: npm run generate
-
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+        
+      - name: Static HTML export with Nuxt
+        run: ${{ steps.detect-package-manager.outputs.manager }} run generate
+        
+      - name: Copy public files
+        run: cp -r public/* .output/public/ || true
+        
+      - name: Add .nojekyll file
+        run: touch .output/public/.nojekyll
+        
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          # Путь вывода для Nuxt 3/4 при статической генерации
           path: ./.output/public
-
-  # Job деплоя
   deploy:
     environment:
       name: github-pages
